# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j_9.4.0-1ubuntu25.04_all.deb
  displayName: 'Download Dummy'

- task: PublishBuildArtifacts@1
  displayName: "Publish artifact"
  inputs:
    ArtifactName: drop
    PathtoPublish: "$(System.DefaultWorkingDirectory)/mysql-connector-j_9.4.0-1ubuntu25.04_all.deb"
